Repository tkaczmarzyk/specification-arg-resolver, pull requests merged in 2022-11, with the labels that each got.

#98 [SAR-97] Added support for join fetch aliases in specification paths
  CHANGELOG.md
  README.md
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/JoinFetch.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/PathSpecification.java
  src/test/java/net/kaczmarzyk/JoinAndJoinFetchReferringToTheSameTableTest.java
  src/test/java/net/kaczmarzyk/JoinE2eTest.java
  src/test/java/net/kaczmarzyk/JoinFetchE2eTest.java
  src/test/java/net/kaczmarzyk/MultiLevelFetchJoinE2eTest.java
  src/test/java/net/kaczmarzyk/MultiLevelJoinE2eTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/CustomerDto.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/IntegrationTestBase.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/utils/ThrowableAssertions.java
  src/test/java/net/kaczmarzyk/utils/interceptor/InterceptedStatementsAssert.java
Labels: type: enhancement, status: waiting-for-final-review

#113 Preserves rootCache variable for uses same join in many @Spec
  CHANGELOG.md
  README.md
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/Join.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/utils/Converter.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/utils/QueryContext.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/web/WebRequestQueryContext.java
  src/test/java/net/kaczmarzyk/JoinE2eTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/utils/converter/ConverterTest.java
  src/test/java/net/kaczmarzyk/utils/interceptor/InterceptedStatementsAssert.java
Labels: type: confirmed-bug, status: waiting-for-the-reporter, status: missing-tests

#136 Code refactoring
  CHANGELOG.md
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/Join.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/utils/Converter.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/web/WebRequestQueryContext.java
  src/test/java/net/kaczmarzyk/JoinE2eTest.java
Labels: status: waiting-for-merge

#108 timestamp conversion support
  README.md
  src/main/java/net/kaczmarzyk/spring/data/jpa/utils/Converter.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/utils/converter/StringToTimestampConverterTest.java
Labels: type: enhancement, status: waiting-for-merge

#139 JoinFetch to Join translation for count queries with filtering applied to fetched associations
  CHANGELOG.md
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/Join.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/JoinFetch.java
  src/test/java/net/kaczmarzyk/FilteringOnJoinFetchInPageableQueryTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/CustomerBuilder.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/Order.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/OrderBuilder.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/JoinFetchInCountQueryTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/utils/converter/StringToCalendarConverterTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/utils/converter/StringToDateConverterTest.java
  src/test/java/net/kaczmarzyk/utils/LoggedQuery.java
  src/test/java/net/kaczmarzyk/utils/LoggedQueryAssertions.java
  src/test/resources/application.properties
  src/test/resources/hibernate.properties
Labels: status: waiting-for-review

#121 Add json request body support for specification values
  README.md
  pom.xml
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/ParamType.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/utils/IOUtils.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/utils/JsonUtils.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/web/SimpleSpecificationResolver.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/web/WebRequestProcessingContext.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/web/annotation/Spec.java
  src/test/java/net/kaczmarzyk/RequestBodyHandlingE2eTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/utils/JsonUtilsTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/web/SimpleSpecificationResolverPathVariablesTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/web/SimpleSpecificationResolverTest.java
Labels: type: enhancement, status: waiting-for-the-reporter
