Repository tkaczmarzyk/specification-arg-resolver, pull requests merged in 2022-12, with the labels that each got.

#148 Fixed bug in SpecificationBuilder that was creating doubled query conditions
  CHANGELOG.md
  src/main/java/net/kaczmarzyk/spring/data/jpa/web/StandaloneProcessingContext.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/utils/SpecificationBuilderTest.java
Labels: status: waiting-for-merge

#146 Refactored json support approach (removed ParamType)
  README.md
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/ParamType.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/web/SimpleSpecificationResolver.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/web/annotation/Spec.java
  src/test/java/net/kaczmarzyk/RequestBodyHandlingE2eTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/web/SimpleSpecificationResolverJsonPathsTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/web/SimpleSpecificationResolverPathVariablesTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/web/SimpleSpecificationResolverTest.java
Labels: status: in-progress

#163 Added additional tests for content-type headers containing directives.
  CHANGELOG.md
  src/test/java/net/kaczmarzyk/RequestBodyHandlingE2eTest.java
Labels: status: waiting-for-final-review

#161 Added setting default time during conversion from date to time storing formats
  CHANGELOG.md
  README.md
  src/main/java/net/kaczmarzyk/spring/data/jpa/utils/Converter.java
  src/test/java/net/kaczmarzyk/E2eTestBase.java
  src/test/java/net/kaczmarzyk/e2e/converter/InstantE2eTest.java
  src/test/java/net/kaczmarzyk/e2e/converter/LocalDateTimeE2eTest.java
  src/test/java/net/kaczmarzyk/e2e/converter/OffsetDateTimeE2eTest.java
  src/test/java/net/kaczmarzyk/e2e/converter/TimestampE2eTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/Customer.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/CustomerBuilder.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/utils/converter/StringToCalendarConverterTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/utils/converter/StringToDateConverterTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/utils/converter/StringToInstantConverterTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/utils/converter/StringToLocalDateTimeConverterTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/utils/converter/StringToOffsetDateTimeConverterTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/utils/converter/StringToTimestampConverterTest.java
Labels: status: waiting-for-final-review

#160 Introduced InTheFuture and InThePast specifications.
  CHANGELOG.md
  README.md
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/InTheFuture.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/InThePast.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/ComparableTestBase.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/ComparableWithConverterTestBase.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/Customer.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/GreaterThanOrEqualTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/GreaterThanTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/InTheFutureTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/InThePastTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/LessThanOrEqualTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/LessThanTest.java
Labels: status: waiting-for-final-review
