Repository tkaczmarzyk/specification-arg-resolver, pull requests merged in 2023-01, with the labels that each got.

#185 Locale support
  CHANGELOG.md
  README.md
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/EqualIgnoreCase.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/LikeIgnoreCase.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/LocaleAware.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/NotEqualIgnoreCase.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/utils/Converter.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/utils/SpecificationBuilder.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/web/SimpleSpecificationResolver.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/web/SpecificationArgumentResolver.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/web/SpecificationFactory.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/IntegrationTestBase.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/IntegrationTestBaseWithConfiguredConversionService.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/EndingWithIgnoreCaseTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/EqualIgnoreCaseLocaleIntegrationTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/LikeIgnoreCaseLocaleIntegrationTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/LikeIgnoreCaseTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/NotEqualIgnoreCaseLocaleIntegrationTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/NotEqualIgnoreCaseTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/StartingWithIgnoreCaseTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/utils/ConverterFallbackMechanismTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/utils/SimpleSpecificationGenerator.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/utils/SpecificationBuilderTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/utils/converter/ConverterTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/utils/converter/StringToCalendarConverterTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/utils/converter/StringToDateConverterTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/utils/converter/StringToInstantConverterTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/utils/converter/StringToLocalDateConverterTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/utils/converter/StringToLocalDateTimeConverterTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/utils/converter/StringToOffsetDateTimeConverterTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/utils/converter/StringToTimestampConverterTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/web/AnnotatedConjunctionSpecInterfaceArgumentResolverTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/web/AnnotatedDisjunctionSpecInterfaceArgumentResolverTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/web/AnnotatedSpecInterfaceArgumentResolverTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/web/AnnotatedSpecInterfaceTestBase.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/web/AnnotatedSpecInterfaceWithComplexInheritanceTreeTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/web/ResolverTestBase.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/web/SimpleSpecificationResolverConstValueSpELSupportIntegrationTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/web/SimpleSpecificationResolverDefaultValueIntegrationTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/web/SimpleSpecificationResolverJsonPathsTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/web/SimpleSpecificationResolverSpecConstructorTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/web/SimpleSpecificationResolverTest.java
  src/test/java/net/kaczmarzyk/utils/ReflectionUtils.java
Labels: status: in-progress

#205 Added fallback method invocation for proxy which does not support the given method directly
  src/main/java/net/kaczmarzyk/spring/data/jpa/web/EnhancerUtil.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/web/EnhancerUtilTest.java
Labels: status: waiting-for-final-review

#204 Introduced `Empty`, `isEmpty` and `isNotEmpty` specifications
  CHANGELOG.md
  README.md
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/Empty.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/IsEmpty.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/IsNotEmpty.java
  src/test/java/net/kaczmarzyk/EmptyE2eTest.java
  src/test/java/net/kaczmarzyk/IsEmptyE2eTest.java
  src/test/java/net/kaczmarzyk/IsNotEmptyE2eTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/Customer.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/CustomerBuilder.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/EmptyTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/IsEmptyTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/IsNotEmptyTest.java
Labels: status: waiting-for-final-review

#215 Updated `springdoc-openapi` dependency for migration to spring boot 3.0
  CHANGELOG.md
  README.md
  pom.xml
  src/main/java/net/kaczmarzyk/spring/data/jpa/swagger/springdoc/SpecificationArgResolverSpringdocOperationCustomizer.java
Labels: status: waiting-for-final-review

#216 Refactored `IsMember` and `IsNotMember` specifications
  CHANGELOG.md
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/IsMember.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/IsNotMember.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/utils/ClassTypeReflectionUtils.java
Labels: status: waiting-for-final-review

#189 Lazy join fix
  CHANGELOG.md
  README.md
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/Join.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/True.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/web/annotation/Join.java
  src/test/java/net/kaczmarzyk/AvoidingRedundantJoinE2eTest.java
  src/test/java/net/kaczmarzyk/E2eTestBase.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/Badge.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/Customer.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/ItemTag.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/Movie.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/Order.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/OrderNote.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/Person.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/JoinFetchInCountQueryTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/JoinTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/utils/SpecificationBuilderTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/web/AnnotatedJoinSpecInterfaceArgumentResolverTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/web/AnnotatedJoinsSpecInterfaceArgumentResolverTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/web/AnnotatedRepeatedJoinSpecInterfaceArgumentResolverTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/web/AnnotatedSpecInterfaceWithComplexInheritanceTreeTest.java
  src/test/java/net/kaczmarzyk/utils/TestLogAppender.java
Labels: status: waiting-for-final-review

#218 Removed deprecated items
  CHANGELOG.md
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/DateAfter.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/DateAfterInclusive.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/DateBefore.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/DateBeforeInclusive.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/DateBetween.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/EqualEnum.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/nativeimage/SpecificationArgumentResolverHintRegistrar.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/web/JoinsSpecificationResolver.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/web/SpecificationFactory.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/web/annotation/JoinFetch.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/web/annotation/Joins.java
  src/test/java/net/kaczmarzyk/AvoidingRedundantJoinE2eTest.java
  src/test/java/net/kaczmarzyk/DateInclusiveE2eTest.java
  src/test/java/net/kaczmarzyk/JoinE2eTest.java
  src/test/java/net/kaczmarzyk/e2e/annotated/AnnotatedSpecInterfaceJoinsE2eTest.java
  src/test/java/net/kaczmarzyk/e2e/converter/DateE2eTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/ConjunctionTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/DateAfterInclusiveTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/DateAfterTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/DateBeforeInclusiveTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/DateBeforeTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/DateBetweenTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/nativeimage/SpecificationArgumentResolverHintRegistrarTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/utils/SimpleSpecificationGenerator.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/web/AnnotatedJoinsSpecInterfaceArgumentResolverTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/web/AnnotatedSpecInterfaceWithComplexInheritanceTreeTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/web/ResolverTestBase.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/web/SimpleSpecificationResolverPathVariablesTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/web/SimpleSpecificationResolverTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/web/SpecificationArgumentResolverTest.java
Labels: status: waiting-for-final-review

#223 Fixed `InTheFuture` and `InThePast` specifications
  CHANGELOG.md
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/InTheFuture.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/InThePast.java
  src/test/java/net/kaczmarzyk/e2e/converter/LocalDateTimeE2eTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/InTheFutureTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/InThePastTest.java
Labels: status: waiting-for-merge

#225 Fixed `InTheFuture` and `InThePast` specifications for 2.x
  CHANGELOG.md
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/InTheFuture.java
  src/main/java/net/kaczmarzyk/spring/data/jpa/domain/InThePast.java
  src/test/java/net/kaczmarzyk/e2e/converter/LocalDateTimeE2eTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/InTheFutureTest.java
  src/test/java/net/kaczmarzyk/spring/data/jpa/domain/InThePastTest.java
Labels: status: waiting-for-merge
